name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run a one-line script
      run: echo Build


  deploy-dev:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'https://br.pinterest.com'
      needs: build
    steps:
    - name: Run a one-line script
      run: echo Deploy dev


  deploy-hmg:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'https://br.pinterest.com'
      needs: deploy-dev
    steps:
    - name: Run a one-line script
      run: echo Deploy hmg


  deploy-prd:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'https://br.pinterest.com'
      needs: deploy-hmg
    steps:
    - name: Run a one-line script
      run: echo Deploy prd
